server:
  port: 8080
  context-path: /hacknight
spring:
  application:
    name: hacknight-backend
  datasource:
    url: jdbc:mysql://localhost:3306/hacknight_alexa?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
#logging:
#  level:
#     org.springframework.security: DEBUG